apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: gp3
