controller:
  image:
    repository: "jenkins/jenkins"
    tag: "lts"
  installPlugins:
    - kubernetes:4285.v50ed5f624918
    - workflow-aggregator:600.vb_57cdd26fdd7
    - credentials-binding:681.vf91669a_32e45
    - git:5.4.0
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  nodeSelector:
    "kubernetes.io/os": linux
  tolerations:
    - key: "key"
      operator: "Equal"
      value: "value"
      effect: "NoSchedule"

persistence:
  enabled: true
  size: 8Gi
  storageClass: "gp3"

agent:
  enabled: true
  image:
    repository: "jenkins/inbound-agent"
    tag: "4.3-4"
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

rbac:
  create: true

serviceAccount:
  create: true
