controller:
  image:
    repository: "jenkins/jenkins"
    tag: "lts"
  installPlugins:
    - kubernetes:1.29.4
    - workflow-aggregator:2.6
    - credentials-binding:1.24
    - git:4.7.1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  nodeSelector:
    "kubernetes.io/os": linux
  tolerations:
    - key: "key"
      operator: "Equal"
      value: "value"
      effect: "NoSchedule"

persistence:
  enabled: true
  size: 8Gi
  storageClass: "efs"

agent:
  enabled: true
  image:
    repository: "jenkins/inbound-agent"
    tag: "4.3-4"
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

rbac:
  create: true

serviceAccount:
  create: true
