- name: Load nvm and install Node.js
  become: yes
  shell: |
    source /home/ubuntu/.nvm/nvm.sh
    nvm install 14  # Example for Node.js 14.x, adjust as needed for compatibility
    nvm alias default 14
    node -e "console.log('Running Node.js ' + process.version)"
  environment:
    HOME: /home/ubuntu
  args:
    executable: /bin/bash
