- name: Install Git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Verify Git installation
  command: git --version
  register: git_version
  changed_when: false

- name: Print Git version
  debug:
    msg: "Git version installed: {{ git_version.stdout }}"
